Repository rohit32999/Netflix-Sign-In-Page, pull requests merged in 2024-01, with the labels that each got.

#19 Password show hide
  Password_show_hide.js
  index.html
  style.css
Labels: apertre

#24 Need Help link redirection
  index.html
  style.css
Labels: easy, apertre, enhancement

#30 Issue #10 solved
  style.css
Labels: Medium, apertre, enhancement

#31 Video background added
  Netflix.mp4
  script.js
  signup.html
  style.css
Labels: Medium, apertre

#40 added logo and background separately
  backgr.jpg
  logoNetflix.png
  signup.html
  style.css
Labels: easy, apertre

#38 made netflix sign in page loook like mobile version
  images/Netflix_Logo_PMS.png
  signup.html
  style.css
Labels: Medium, apertre

#41 fixed responsiveness of signup
  .vscode/settings.json
  signup.html
  style.css
Labels: Hard, apertre

#46 added links to the footer & did minor changes in css (#42)
  main.css
  main.html
Labels: easy, apertre

#50 #48 README.md file
  Files/Netflix.png
  Files/README.md
  Files/css.jpeg
  Files/html.png
  Files/java.jpg
Labels: easy, apertre, documentation

#52 mobile responsivness issue solved
  style.css
Labels: Medium, apertre

#62 addtext
  signup.html
  style.css
Labels: easy, apertre

#64 enchanced ui of the netflix home page(#51)
  main.css
  main.html
Labels: Medium, apertre

#59 signincss
  style.css
Labels: Medium, apertre

#73 issue #70 adding Netflix page of movies
  images/banner (1).jpg
  images/large-movie1.jpg
  images/large-movie2.jpg
  images/large-movie3.jpg
  images/large-movie4.jpg
  images/large-movie5.jpg
  images/large-movie6.jpg
  images/large-movie7.jpg
  images/large-movie8.jpg
  images/netflix-avatar.png
  images/netflix-logo.png
  images/small-movie1.jpg
  images/small-movie2.jpg
  images/small-movie3.jpg
  images/small-movie4.jpg
  images/small-movie5.jpg
  images/small-movie6.jpg
  images/small-movie7.jpg
  images/small-movie8.jpg
  netflix.css
  netflix.html
Labels: Medium, apertre

#74 Update README.md
  README.md
Labels: easy, apertre

#78 Created the signup page
  loginpage/assets/images/bg.jpg
  loginpage/assets/images/img1.png
  loginpage/assets/images/img2.png
  loginpage/assets/images/img3.png
  loginpage/assets/images/img4.png
  loginpage/assets/images/img5.png
  loginpage/assets/images/logo.png
  loginpage/assets/videos/video-devices-in.m4v
  loginpage/assets/videos/video2.m4v
  loginpage/login.css
  loginpage/login.html
  signup.html
Labels: Hard, apertre

#77 css changes for footer made
  main.css
  main.html
  style.css
Labels: easy, apertre

#82 Fix Input Label Vertical Centering
  style.css
Labels: easy, apertre

#89 entire css change in sign up page
  signup.html
  style.css
Labels: Medium, apertre

#90 Update README.md
  README.md
Labels: easy
